name: FOSSA Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          echo "$HOME/.fossa/bin" >> $GITHUB_PATH

      - name: Run FOSSA Scan
        id: fossa
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          set -o pipefail
          fossa analyze 2>&1 | tee fossa_output.txt
          fossa test 2>&1 | tee -a fossa_output.txt

      - name: Parse FOSSA Output and Update package.json
        if: failure()
        run: |
          echo "---- DEBUG: FOSSA OUTPUT ----"
          cat fossa_output.txt
          echo "---- DEBUG: Extracted values ----"
          vuln_pkg=$(grep -Eo '[a-zA-Z0-9._-]+@[0-9.]+' fossa_output.txt | head -n1)
          fixed_ver=$(grep 'Fixed in:' fossa_output.txt | head -n1 | awk '{print $3}')
          echo "vuln_pkg: $vuln_pkg"
          echo "fixed_ver: $fixed_ver"
          if [ -n "$vuln_pkg" ] && [ -n "$fixed_ver" ]; then
            pkg=$(echo $vuln_pkg | cut -d'@' -f1)
            echo "pkg: $pkg"
            echo "Updating $pkg to version $fixed_ver in package.json"
            jq --arg pkg "$pkg" --arg ver "$fixed_ver" '.dependencies[$pkg]=$ver' package.json > tmp.json && mv tmp.json package.json
            npm install
            echo "Updated $pkg to $fixed_ver due to FOSSA vulnerability fix recommendation." > FOSSA_REPORT.md
          else
            echo "No vulnerable package or fixed version found in FOSSA output." > FOSSA_REPORT.md
          fi

      - name: Commit changes if FOSSA failed
        if: failure()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json FOSSA_REPORT.md || true
          git commit -m "chore: update recommended package from FOSSA scan failure" || echo "No changes to commit"

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update recommended package from FOSSA scan failure"
          title: "FOSSA scan failed - recommended package update"
          body: "This PR was created automatically because the FOSSA scan failed. The recommended package update has been applied. See FOSSA_REPORT.md for details."
          branch: fossa-failure-recommended-update